/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './message-input.component.ngfactory';
import * as i2 from './message-input.component';
import * as i3 from './message.service';
import * as i4 from './message-list.component.ngfactory';
import * as i5 from './message-list.component';
import * as i6 from './messages.component';
const styles_MessagesComponent:any[] = ([] as any[]);
export const RenderType_MessagesComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_MessagesComponent,data:{}});
export function View_MessagesComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),4,'div',[['class','row']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),
      ['\n            '])),(_l()(),i0.ɵeld(3,0,(null as any),(null as any),1,'app-message-input',
      ([] as any[]),(null as any),(null as any),(null as any),i1.View_MessageInputComponent_0,
      i1.RenderType_MessageInputComponent)),i0.ɵdid(4,114688,(null as any),0,i2.MessageInputComponent,
      [i3.MessageService],(null as any),(null as any)),(_l()(),i0.ɵted(-1,(null as any),
      ['\n        '])),(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(7,
      0,(null as any),(null as any),0,'hr',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),
      ['\n        '])),(_l()(),i0.ɵeld(9,0,(null as any),(null as any),4,'div',[['class',
      'row']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n            '])),(_l()(),i0.ɵeld(11,0,(null as any),
          (null as any),1,'app-message-list',([] as any[]),(null as any),(null as any),
          (null as any),i4.View_MessageListComponent_0,i4.RenderType_MessageListComponent)),
      i0.ɵdid(12,114688,(null as any),0,i5.MessageListComponent,[i3.MessageService],
          (null as any),(null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n        '])),
      (_l()(),i0.ɵted(-1,(null as any),['\n    ']))],(_ck,_v) => {
    _ck(_v,4,0);
    _ck(_v,12,0);
  },(null as any));
}
export function View_MessagesComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app-messages',
      ([] as any[]),(null as any),(null as any),(null as any),View_MessagesComponent_0,
      RenderType_MessagesComponent)),i0.ɵdid(1,49152,(null as any),0,i6.MessagesComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const MessagesComponentNgFactory:i0.ComponentFactory<i6.MessagesComponent> = i0.ɵccf('app-messages',
    i6.MessagesComponent,View_MessagesComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovbm9kZWpzL25vZGVqcythbmd1bGFyMi8wNyBFcnJvciBIYW5kbGluZy9hdHRhY2hlZF9maWxlcy8wODkgVXNpbmcgYW4gRXJyb3IgU2VydmljZSAgUGFzc2luZyBEYXRhLzA3IEVycm9ycy9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9ub2RlanMvbm9kZWpzK2FuZ3VsYXIyLzA3IEVycm9yIEhhbmRsaW5nL2F0dGFjaGVkX2ZpbGVzLzA4OSBVc2luZyBhbiBFcnJvciBTZXJ2aWNlICBQYXNzaW5nIERhdGEvMDcgRXJyb3JzL2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZXMuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovbm9kZWpzL25vZGVqcythbmd1bGFyMi8wNyBFcnJvciBIYW5kbGluZy9hdHRhY2hlZF9maWxlcy8wODkgVXNpbmcgYW4gRXJyb3IgU2VydmljZSAgUGFzc2luZyBEYXRhLzA3IEVycm9ycy9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC50cy5NZXNzYWdlc0NvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovbm9kZWpzL25vZGVqcythbmd1bGFyMi8wNyBFcnJvciBIYW5kbGluZy9hdHRhY2hlZF9maWxlcy8wODkgVXNpbmcgYW4gRXJyb3IgU2VydmljZSAgUGFzc2luZyBEYXRhLzA3IEVycm9ycy9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC50cy5NZXNzYWdlc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8ZGl2IGNsYXNzPVwicm93XCI+XG4gICAgICAgICAgICA8YXBwLW1lc3NhZ2UtaW5wdXQ+PC9hcHAtbWVzc2FnZS1pbnB1dD5cbiAgICAgICAgPC9kaXY+XG4gICAgICAgIDxocj5cbiAgICAgICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgICAgICAgPGFwcC1tZXNzYWdlLWxpc3Q+PC9hcHAtbWVzc2FnZS1saXN0PlxuICAgICAgICA8L2Rpdj5cbiAgICAiLCI8YXBwLW1lc3NhZ2VzPjwvYXBwLW1lc3NhZ2VzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsa0RBQ1E7TUFBQTtNQUFBLDRDQUFpQjtNQUFBLHFCQUNiO01BQUE7eUNBQUEsVUFBQTtNQUFBLGlEQUF1QztNQUFBLGlCQUNyQyxrREFDTjtNQUFBO01BQUEsNENBQUk7TUFBQSxpQkFDSjtNQUFBO01BQWlCLHNEQUNiO1VBQUE7VUFBQTthQUFBO1VBQUEsNkJBQXFDO01BQ25DO0lBTEY7SUFJQTs7OztvQkNOWjtNQUFBO2tDQUFBLFVBQUE7TUFBQTs7OyJ9
